# Generated by Django 5.0.14 on 2026-05-22 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project'),
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RACIAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('responsible', 'Responsible'), ('accountable', 'Accountable'), ('consulted', 'Consulted'), ('informed', 'Informed')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raci_assignments', to='roster.rosterperson')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raci_assignments', to='projects.project')),
            ],
            options={
                'ordering': ['role', 'person__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='raciassignment',
            constraint=models.UniqueConstraint(fields=('project', 'person', 'role'), name='raci_unique_project_person_role'),
        ),
    ]
