# Generated by Django 5.0.14 on 2026-05-22 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_raciassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion_text', models.TextField()),
                ('vote_date', models.DateField()),
                ('votes_for', models.PositiveIntegerField(default=0)),
                ('votes_against', models.PositiveIntegerField(default=0)),
                ('votes_abstain', models.PositiveIntegerField(default=0)),
                ('minutes_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board_approval', to='projects.project')),
            ],
            options={
                'ordering': ['-vote_date'],
            },
        ),
    ]
