# Generated by Django 5.0.14 on 2026-05-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_updatenote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatenote',
            options={'ordering': ['-created_at', '-pk']},
        ),
    ]
