# Generated by Django 5.0.14 on 2026-05-23 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_generationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatenote',
            options={'ordering': ['-is_pinned', '-created_at', '-pk']},
        ),
        migrations.AddField(
            model_name='updatenote',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updatenote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='updatenote',
            constraint=models.UniqueConstraint(condition=models.Q(('is_pinned', True)), fields=('project',), name='unique_pinned_note_per_project'),
        ),
    ]
