# Generated by Django 5.0.14 on 2026-06-03 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_updatenote_options_updatenote_is_pinned_and_more'),
        ('roster', '0002_rostergroup_groupmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raciassignment',
            name='source_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raci_assignments_via_group', to='roster.rostergroup'),
        ),
    ]
