# Generated by Django 5.0.14 on 2026-05-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_roster_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('bytes_uploaded', models.PositiveIntegerField(blank=True, null=True)),
                ('object_key', models.CharField(blank=True, max_length=200)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-run_date'],
            },
        ),
    ]
