from .approval import approval_add as approval_add
from .approval import approval_edit as approval_edit
from .attachment import attachment_delete as attachment_delete
from .attachment import attachment_download as attachment_download
from .attachment import attachment_upload as attachment_upload
from .board import board_view as board_view
from .bulk import bulk_delete as bulk_delete
from .calendar import calendar_view as calendar_view
from .category import category_add as category_add
from .category import category_delete as category_delete
from .category import category_list as category_list
from .category import category_rename as category_rename
from .checklist import checklist_add as checklist_add
from .checklist import checklist_delete as checklist_delete
from .checklist import checklist_mark_project_complete as checklist_mark_project_complete
from .checklist import checklist_toggle as checklist_toggle
from .csv_import import import_confirm as import_confirm
from .csv_import import import_form as import_form
from .csv_import import import_template as import_template
from .inline import budget_edit as budget_edit
from .inline import budget_save as budget_save
from .inline import budget_show as budget_show
from .inline import dates_edit as dates_edit
from .inline import dates_save as dates_save
from .inline import dates_show as dates_show
from .inline import priority_edit as priority_edit
from .inline import priority_save as priority_save
from .inline import priority_show as priority_show
from .inline import status_edit as status_edit
from .inline import status_save as status_save
from .inline import status_show as status_show
from .inline import vendor_edit as vendor_edit
from .inline import vendor_save as vendor_save
from .inline import vendor_show as vendor_show
from .note import note_add as note_add
from .note import note_delete as note_delete
from .note import note_edit as note_edit
from .note import note_pin as note_pin
from .note import note_save as note_save
from .note import note_show as note_show
from .project_detail import detail as detail
from .project_form import create as create
from .project_form import edit as edit
from .project_list import list_view as list_view
from .raci import raci_add as raci_add
from .raci import raci_add_group as raci_add_group
from .raci import raci_remove as raci_remove
from .recurring import recurring_create as recurring_create
from .recurring import recurring_edit as recurring_edit
from .recurring import recurring_list as recurring_list
from .recurring import recurring_toggle as recurring_toggle
from .report import report_view as report_view
from .search import search_view as search_view
