from .inline import budget_edit as budget_edit
from .inline import budget_save as budget_save
from .inline import budget_show as budget_show
from .inline import dates_edit as dates_edit
from .inline import dates_save as dates_save
from .inline import dates_show as dates_show
from .inline import priority_edit as priority_edit
from .inline import priority_save as priority_save
from .inline import priority_show as priority_show
from .inline import status_edit as status_edit
from .inline import status_save as status_save
from .inline import status_show as status_show
from .inline import vendor_edit as vendor_edit
from .inline import vendor_save as vendor_save
from .inline import vendor_show as vendor_show
from .note import note_add as note_add
from .project_detail import detail as detail
from .project_form import create as create
from .project_form import edit as edit
from .project_list import list_view as list_view
